export const projects = [
	{
		title: 'I can help you with',
		description: `Set Decoration & Styling :
Crafting visually rich environments that bring depth, authenticity, and character to every frame.`,
		description2: `Art Direction :
Guiding the creative vision of film and series productions with a balance of aesthetics and storytelling.`,
		description3: `Visual Storytelling :
Translating scripts into immersive worlds where design supports emotion and narrative.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759927973/israr2_vcuqow.png',
		color: '#e9e1cb',
	},

	{
		title: 'Shaping Visual Stories :\nA showcase of selected projects where strategy meets creativity, highlighting the skills, tools, and vision I bring to every collaboration.',
		description: ``,
		description2: ``,
		description3: ``,
		src: 'back.png',
		color: '#e9e1cb',
	},
    {
		title: '"Sondos (Season 2)" – Saudi television series – Saudi Arabia – 2024',
		description: `Set Decoration & Visual Continuity: Designed and dressed sets that preserved the series’ signature aesthetic while introducing new elements to reflect the emotional evolution of the story.`,
		description2: `Atmospheric Detailing: Used color palettes, props, and textures to evoke both modern refinement and cultural authenticity — creating spaces that visually communicate character depth.`,
		description3: `Narrative Support: Enhanced the director’s vision by shaping immersive environments that heighten the trailer’s emotional impact and reinforce the tone of Season 2.`,
		src: 'https://res.cloudinary.com/drbydzhzz/video/upload/v1759930684/sondos_qh4xvo.mp4',
		color: '#edeae7',
	},
	{
		title: '"Lel Mout 2" – Shahid Original Series – Saudi Arabia – (Ramadan 2022)',
		description: `Cinematic Set Decoration: Designed emotionally charged environments that visually echo the intensity and drama of the storyline, enhancing the series’ dark romantic atmosphere.`,
		description2: `Symbolic Detailing: Integrated color palettes, props, and textures to represent conflict, love, and betrayal—amplifying the psychological depth of each scene.`,
		description3: `Collaboration & Execution: Worked closely with directors and production teams to ensure visual consistency across episodes, maintaining the high-end aesthetic of Shahid’s Ramadan productions.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759927881/lelmout1_gyiazc.png',
		color: '#e5e2de',
	},
	{
		title: '"Barzakh" – Short film - Tunisia - (2024)',
		description: `Décor – Barzakh (The Dying Of The Light):
Created immersive set pieces that captured the film’s mystical and symbolic atmosphere.`,
		description2: `Shaped visual spaces that bridge reality and the afterlife, enhancing the teaser’s haunting tone.`,
		description3: `Collaborated closely with the director to translate abstract themes into tangible cinematic environments.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759927929/barzakh_cbj1lt.jpg',
		link: 'https://www.youtube.com/watch?v=nczb3f3JToc',
		color: '#ded9d5',
	},
	{
		title: '"Aljayda" – Film - Tunisia - 2020)',
		description: `Decor – El Jaida (Film by Selma Baccar) Feature Film : Designed historically authentic set environments reflecting 1950s Tunisia.`,
		description2: `Enhanced the emotional depth of women’s struggles through symbolic décor choices.`,
        description3: `Supported the director’s vision by blending realism with cultural storytelling.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759927851/aljayda_bzzm9g.png',
		link: 'https://www.youtube.com/watch?v=452F_EOlNkU',
		color: '#d6d1cb',
	},
	{
		title: '"Metier" - Short film - Tunisia - (2022)',
		description: `Set Design for Personal Empowerment: Crafted environments that visually represent the journey of individuals finding pride and purpose in their professions.`,
		description2: `Authentic Visual Storytelling: Designed spaces that resonate with the film's message, enhancing the narrative of overcoming societal judgments.`,
		description3: `Collaborative Creative Process: Worked closely with the director and production team to ensure the set design aligned with the film's vision and themes.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759927952/metier_co4cgb.png',
		link: 'https://www.youtube.com/watch?app=desktop&v=gu2sN5I9hko&fbclid=IwRlRTSANJBsxleHRuA2FlbQIxMQABHvYLixR30BJNq--W-5tEOWjNZyq6QjHZj1iqd_Hw68QIR1HSmWF2douJsXiN_aem_-8TrJcyjNBAk_JNwN36RqQ&d=w',
		color: '#cfc8c2',
	},
	{
		title: '"TEASER_POUSSIERE_V02" - Film - Tunisia - (2021)',
		description: `Set Conceptualization: Designed a set that encapsulated the project's theme, providing a visual foundation for the teaser.`,
		description2: `Artistic Direction: Collaborated with the creative team to ensure the set aligned with the desired aesthetic and mood.`,
		description3:`Implementation: Managed the construction and styling of the set, ensuring all elements were in place for the shoot.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759928020/teaser_yuwhqp.png',
		link: 'https://vimeo.com/493695298?fbclid=IwZnRzaANJBnFleHRuA2FlbQIxMQABHgJyRTtq6Im2WIxn6ZN5qUQK3R6QuEfxiaWAbzO0VdFQz5CpWxc3aTQCo64m_aem_BUaL_OswFc-BvqAO7pX8ng',
		color: '#c7c0b9',
	},
	{
		title: '"Yemma (Season 1)" - Serie - Algeria - (2020)',
		description: `Cultural Authenticity in Design: Developed sets that authentically represent Tunisian heritage, enhancing the film's cultural narrative.`,
		description2: `Visual Storytelling: Designed environments that reflect the emotional depth and themes of the film, supporting the director's vision.`,
		description3: `Set Construction & Management: Oversaw the building and arrangement of sets, ensuring timely and efficient execution within budget constraints.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759928057/yemma_kp0fsl.png',
		link: 'https://www.youtube.com/playlist?list=PLjMAptVPZlQtQ-ibpJqG7t2xXkifIoF_O',
		color: '#c0b7b0',
	},
	{
		title: '"Yemma (Season 2)" - Serie - Algeria - (2021)',
		description: `Artistic Set & Visual Design: Contributed to the visual mood and design elements featured in the opening credits, blending traditional and modern aesthetics to reflect the series’ emotional themes.`,
		description2: `Creative Collaboration: Worked alongside TMV Studios and Red Bolt Design to ensure a cinematic and cohesive opening sequence matching the tone of the show.`,
		description3: `Cultural Expression: Integrated motifs and textures inspired by North African identity, enhancing the authenticity and visual storytelling of the series’ introduction.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759928091/yemma2_dbg8h5.png',
		color: '#b8afa6',
	},
	{
		title: '"KAMIKAZ" – Short Film (Official Competition, 13th National Festival of Professional Short Films) - Tunis - (2024)',
		description: `Visual Storytelling: Crafted the cinematography and scene composition to amplify tension, emotion, and narrative flow, translating complex themes into striking visuals.`,
		description2: `Art Direction & Mood Design: Developed the visual tone, lighting, and spatial dynamics to balance realism with poetic cinematic expression.`,
		description3: `Impact & Recognition: The film’s aesthetic and storytelling contributed to its selection in the official competition, reinforcing its emotional and artistic resonance with audiences.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759927991/kamikaz_exe9am.jpg',
		color: '#b0a79d',
	},
	{
		title: '"CHOUERREB (Saison 2)" – historical series - Tunisia - (2019)',
		description: `Set Decoration & Styling: Contributed to the visual authenticity of the series by designing and dressing environments that reflect the raw energy and social texture of Tunisian street life.`,
		description2: `Cinematic Atmosphere: Balanced realism with dramatic tension through detailed prop selection, color coordination, and spatial arrangement — enhancing the emotional depth of each scene.`,
		description3: `Cultural Resonance: Helped shape a setting that immerses viewers in the narrative’s cultural and psychological layers, supporting the director’s vision with strong visual storytelling.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759927958/chwerreb_p7bdzz.png',
		link: 'https://www.youtube.com/watch?v=fAPbAw11Ipc&list=PLTGtCMX0-RuJw1WAcVFLygPidbGJqljpP',
		color: '#a99e94',
	},
	{
		title: '"DIMAW - DC" - Short film - Tunisia - (2024)',
		description: `Transforming Spaces: Crafted visually striking sets that bring the director’s vision to life, turning abstract ideas into tangible environments.`,
		description2: `Story-Driven Design: Chose and arranged décor to enhance the mood, tone, and narrative flow of each scene.`,
		description3: `Seamless Collaboration: Coordinated with the production and camera teams to ensure the set design elevated every shot.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759928085/Dimaw_nu6dnd.png',
		link: 'https://vimeo.com/922189427?fbclid=IwZnRzaANJB15leHRuA2FlbQIxMQABHr-3gtjgR8s5SsjBwUzbZaQeDtiaq6NYoE4i88b7QmAN1fk7mTsf6j5CQilR_aem_EpdSHlE5CAYzVsVUqsitww',
		color: '#a1968b',
	},
	{
		title: '"KASO" – MESSYEBA (INTRO – EP FEELINGS)  Music Video - Tunisia - (2024)',
		description: `Creative Set Design: Conceived and executed visually striking sets that reflect the mood and narrative of the song, enhancing the storytelling experience.`,
		description2: `Collaboration with Production Team: Worked closely with directors, cinematographers, and stylists to ensure each set complements the video’s artistic direction.`,
		description3: `Project Management & Execution: Oversaw the construction and arrangement of set elements, ensuring smooth workflow on set and a polished final look.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759928040/kaso_gp8yos.png',
		link: 'https://www.youtube.com/watch?v=glL4e1BZscM',
		color: '#9a8d81',
	},
	{
		title: 'KASO – MECHI W MKHOLI (BOX PERFORMANCE / FEELINGS) Music Video - Tunisia',
		description: `Artistic Set Direction: Designed immersive and visually engaging sets that capture the energy and mood of the performance.`,
		description2: `Team Collaboration: Coordinated with the director, cinematographer, and production team to align sets with the overall visual storytelling.`,
		description3: `Execution & Oversight: Managed the construction and styling of set elements, ensuring consistency, detail, and high-quality presentation.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759928098/kaso2_bxkf6k.png',
		link: 'https://www.youtube.com/watch?v=HXawfpVtX6U',
		color: '#928578',
	},
	{
		title: 'KASO – “Melli Sar” (Box Performance – Feelings) - Tunisia',
		description: `Visual Identity & Set Direction: Participated in crafting a minimalist yet powerful performance setup that visually amplifies KASO’s emotional delivery. The concept balances raw authenticity with refined cinematic aesthetics.`,
		description2: `Creative Intent:
Designed the mood and spatial composition to highlight feelings as the core theme — using contrast, lighting, and camera framing to translate emotion into atmosphere.`,
		description3: `Impact:
The performance garnered over 1 million views, showcasing the strength of visual storytelling in amplifying musical emotion.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759927994/kaso3_iflnva.png',
		link: 'https://www.youtube.com/watch?v=0zTv0G82Yp8&list=RD0zTv0G82Yp8&start_radio=1',
		color: '#8b7c6f',
	},
	{
		title: 'Decor – "A.L.A “IDK”" - Music Video - Tunisia - (2023)',
		description: `Curated and styled set decoration to enhance the video’s cinematic atmosphere.`,
		description2: `Translated the director’s vision into authentic, mood-driven environments.`,
		description3: `Added depth and visual cohesion, elevating the storytelling and aesthetic impact.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759927960/aala_jeugix.png',
		link: 'https://www.youtube.com/watch?v=C3q0aWKd8mw',
		color: '#837466',
	},
	{
		title: 'Set Designer – "MADD" — DRIVE (feat. SNOR)  Music Video - Marroco - (2024)',
		description: `Designed and built impactful set pieces that amplified the music video’s bold and cinematic aesthetic.`,
		description2: `Translated the creative vision into immersive visuals, balancing modern styling with symbolic details.`,
		description3: `Collaborated with directors, stylists, and production teams to ensure seamless integration of set design into the storytelling.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759927904/madd_vmfwxp.png',
		link: 'https://www.youtube.com/watch?v=EJE_Amw-5zI',
		color: '#7b6c5c',
	},
	{
		title: '"Yaychek" - BH Director’s Cut - Tunisia - (2024)',
		description: `Set Design & Styling: Crafted the visual environment, ensuring each element aligned with the artistic vision.`,
		description2: `Collaboration with Creative Team: Worked closely with the director and creatives to enhance storytelling through the set.`,
		description3: `Attention to Detail: Selected props, backdrops, and décor elements to immerse the audience in the scene.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759928100/bh_qzl1kk.png',
		link: 'https://vimeo.com/922638236?fbclid=IwZnRzaANJB29leHRuA2FlbQIxMQABHkazH6nZQgxKOgLX-06GrlOVN2RTVfjr2Et3e3Ba17KtyvS2uQ72GqWI2CfQ_aem_j4_j2GJcKaS3O97njlNM4A',
		color: '#746353',
	},
	{
		title: '"Moussa Fennira" – Short film - Tunisia - (2023)',
		description: `Designed and built authentic sets that visually anchored the narrative, enhancing the emotional journey of the protagonist.`,
		description2: `Collaborated with the director, cinematographer, and production team to create seamless visual atmospheres that aligned with the film’s creative vision.`,
		description3: `Led the art department, managing assistants and on-site construction to deliver impactful environments on tight production schedules.`,
		src: 'https://res.cloudinary.com/drbydzhzz/image/upload/v1759928006/moussa_tr0wxn.png',
		link: 'https://www.instagram.com/reel/DFQHZJqsfH2/?igsh=MTljcG5peTN5Y3Vjag%3D%3D',
		color: '#6c5b4a',
	},
	{
		title: '"IZI" – Zitouna Payment (Advertisement Vidéo) - Tunisia - (2024)',
		description: `Visual Environment Crafting: Created sets that emphasize convenience, modernity, and ease—reinforcing the brand message of seamless financial services.`,
		description2: `Brand-Centric Design: Integrated the logo, color palette, and visual identity of IZI into the décor to keep the imagery consistent with branding.`,
		description3: `Emotional Connection through Space: Built environments that feel relatable and human, making viewers connect with the service’s promise of comfort and trust.`,
		src: 'https://res.cloudinary.com/drbydzhzz/video/upload/v1759930274/Zitouna_kk805k.mp4',
		link: '',
		color: '#655241',
	},
	{
		title: '"CRK Maroquinerie" – Winter Campaign “Touch The Gold” - Tunisia - (2024)',
		description: `Luxury-Centric Visual Design :
Developed refined set environments that highlight the elegance of CRK’s leather goods, ensuring every frame reflects sophistication and exclusivity.`,
		description2: `Artistic Use of Contrast & Texture :
Balanced golden hues with minimalist backdrops to create a striking interplay between the products and their surroundings.`,
		description3: `Fashion & Brand Alignment :
Collaborated closely with stylists and photographers to craft a visual atmosphere that embodies CRK’s identity—modern, bold, and aspirational.`,
		src: 'https://res.cloudinary.com/drbydzhzz/video/upload/v1759930529/CRK_jcx5dh.mp4',
		link: '',
		color: '#5d4a37',
	},
	{
		title: '"Maxxx Chips" – AFCON 2024 Campaign - Tunisia - (2024)',
		description: `Sports-Inspired Visual Storytelling :
Designed dynamic visuals that capture the passion of football, blending national pride with the energy of AFCON 2024.`,
		description2: `Youth-Oriented Creative Direction :
Delivered vibrant, fast-paced imagery to connect with young audiences, reinforcing Maxxx Chips as a fun and energetic brand.`,
		description3: `Seamless Brand Integration :
Balanced football culture and product placement, ensuring the campaign resonates emotionally while keeping the brand front and center.`,
		src: 'https://res.cloudinary.com/drbydzhzz/video/upload/v1759930782/Chips_s9katp.mp4',
		link: '',
		color: '#56412e',
	},
	{
		title: '"Xiaomi" – Redmi Note 11 Series "Rise to the Challenge" - Tunisia - (2023)',
		description: `odern Tech Aesthetics :
Created sleek and innovative set designs to highlight the cutting-edge features of the Redmi Note 11 Series.`,
		description2: `Youthful & Energetic Visuals :
Developed bold and colorful ambiances that resonate with Xiaomi’s young, dynamic audience.`,
		description3: `Seamless Product Highlighting :
Ensured the phone’s design and lifestyle appeal remained at the heart of the campaign through striking visual storytelling.`,
		src: 'https://res.cloudinary.com/drbydzhzz/video/upload/v1759929238/Xiaomi_zh3esl.mp4',
		link: '',
		color: '#4e3925ff',
	},
];
